let events=[];let selectedMonth=new Date().getMonth();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const cities={Canada:['Vancouver','Richmond','Burnaby','Surrey','Coquitlam','New Westminster','Delta','Langley','Victoria','Kelowna','Whistler','Squamish','Calgary','Edmonton','Toronto','Ottawa'],USA:['Seattle','Portland','San Francisco','Los Angeles','New York','Chicago','Miami']};
async function init(){try{events=await (await fetch('/data/events.json')).json()}catch(e){events=[]}setupNav();populateFilters();setupDatePicker();renderCards();renderCalendar();}
function setupNav(){const login=$('#loginBtn'); if(login) login.onclick=()=>$('#loginModal').classList.add('open'); $$('.close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));}
function populateFilters(){const country=$('#country'),city=$('#city'); if(!country||!city)return; country.onchange=()=>{city.innerHTML=cities[country.value].map(c=>`<option>${c}</option>`).join(''); renderCards();}; country.onchange(); ['city','eventDate'].forEach(id=>{const el=$('#'+id); if(el) el.onchange=()=>renderCards();}); const btn=$('#exploreBtn'); if(btn) btn.onclick=()=>renderCards();}
function setupDatePicker(){const input=$('#eventDate'); if(!input)return; const today=new Date(); const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; input.min='2026-01-01'; input.max='2026-12-31'; $$('.dateQuick button').forEach(btn=>{btn.onclick=()=>{const type=btn.dataset.dateQuick; if(type==='clear'){input.value=''; renderCards(); return;} if(type==='today'){input.value=iso(today); selectedMonth=today.getMonth(); renderCards(); renderCalendar(); return;} if(type==='weekend'){const d=new Date(today); const day=d.getDay(); const add=(6-day+7)%7 || 0; d.setDate(d.getDate()+add); input.value=iso(d); selectedMonth=d.getMonth(); renderCards(); renderCalendar();}}});}
function eventCoversDate(ev,date){return ev.date<=date && (ev.endDate||ev.date)>=date;}
function filtered(){const country=$('#country')?.value||'Canada'; const city=$('#city')?.value||'Vancouver'; const date=$('#eventDate')?.value||''; return events.filter(e=>e.country===country&&e.city===city&&(!date||eventCoversDate(e,date)));}
function renderCards(){const grid=$('#eventGrid'); if(!grid)return; const list=filtered(); const country=$('#country')?.value||'Canada'; const city=$('#city')?.value||'Vancouver'; const fallback=events.filter(e=>e.country===country&&e.city===city); const show=list.length?list:(fallback.length?fallback:events.slice(0,8)); grid.innerHTML=show.map(card).join(''); const head=document.querySelector('#events .sectionHead h2'); if(head){const date=$('#eventDate')?.value; head.textContent=date?`Events on ${fmt(date)}`:`${city} Picks`;}}
function card(e){return `<article class="card"><img src="${e.image}" alt="${e.title}"><div class="cardBody"><span class="pill">${e.category}</span><h3>${e.title}</h3><p>${fmt(e.date)}${e.endDate&&e.endDate!==e.date?' – '+fmt(e.endDate):''}</p><p>${e.location}</p><p>${e.description}</p></div><div class="cardActions"><button class="miniBtn" onclick='saveEvent(${JSON.stringify(e).replace(/'/g,"&apos;")})'>Save</button><a class="miniBtn" href="${gcal(e)}" target="_blank">Google Calendar</a></div></article>`}
function fmt(d){return new Date(d+'T00:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'})}
function gcal(e){const start=e.date.replaceAll('-',''); const end=(e.endDate||e.date).replaceAll('-',''); return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(e.title)}&dates=${start}/${end}&details=${encodeURIComponent(e.description)}&location=${encodeURIComponent(e.location)}`}
function saveEvent(e){const saved=JSON.parse(localStorage.getItem('nomadx_saved')||'[]'); if(!saved.find(x=>x.id===e.id))saved.push(e); localStorage.setItem('nomadx_saved',JSON.stringify(saved)); alert('Saved to My Moves');}
function renderCalendar(){const months=$('#months'),cal=$('#calendar'); if(!months||!cal)return; months.innerHTML=Array.from({length:12},(_,i)=>`<button class="monthBtn ${i===selectedMonth?'active':''}" onclick="selectedMonth=${i};renderCalendar();document.getElementById('calendar-section').scrollIntoView({behavior:'smooth'})">${new Date(2026,i,1).toLocaleDateString('en-CA',{month:'long'})}</button>`).join(''); const year=2026; const first=new Date(year,selectedMonth,1); const days=new Date(year,selectedMonth+1,0).getDate(); const offset=first.getDay(); let cells=''; for(let i=0;i<offset;i++)cells+='<div></div>'; for(let d=1;d<=days;d++){const date=`${year}-${String(selectedMonth+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`; const evs=events.filter(e=>e.date<=date&&(e.endDate||e.date)>=date); cells+=`<button class="day" onclick="pickCalendarDate('${date}')"><strong>${d}</strong>${evs.slice(0,2).map(e=>`<span class="dot">${e.title}</span>`).join('')}</button>`} cal.innerHTML=`<h2>${new Date(year,selectedMonth,1).toLocaleDateString('en-CA',{month:'long',year:'numeric'})}</h2><p class="muted">Click any day to filter event cards above.</p><div class="calendarGrid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<b>${x}</b>`).join('')}${cells}</div>`;}
function pickCalendarDate(date){const input=$('#eventDate'); if(input){input.value=date; selectedMonth=new Date(date+'T00:00:00').getMonth(); renderCards(); window.location.hash='events';}}
function renderMember(){const box=$('#savedList'); if(!box)return; const saved=JSON.parse(localStorage.getItem('nomadx_saved')||'[]'); box.innerHTML=saved.length?saved.map(card).join(''):'<p class="muted">No saved moves yet. Save events from Explore.</p>';}
init().then(renderMember);
